server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/healthlink-config/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo/

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
